zeebe:
  client:
    connection-mode: ADDRESS
    broker:
      gateway-address: 127.0.0.1:26500
    security:
      plaintext: true
    default-job-worker-tenant-ids:

server:
  error:
    include-message: always
  port: 7081

storage:
  database:
    url: postgresql://localhost:5432/insurance
    username: postgres
    password: postgres

spring:
  application:
    name: isurance-service
  r2dbc:
    url: r2dbc:${storage.database.url}
    username: ${storage.database.username}
    password: ${storage.database.password}
    pool:
      enabled: true
      initial-size: 10
      max-size: 30
      max-idle-time: 1m
  flyway:
    url: jdbc:${storage.database.url}
    user: ${storage.database.username}
    password: ${storage.database.password}
    baseline-on-migrate: true
    baseline-version: 0
    clean-on-validation-error: false
