zeebe:
  client:
    cloud:
      region: jfk-1
      clusterId: d94b4bc3-d0ab-4046-a3e4-543e82d4840e
      clientId: GfdvNzYFS8fKVTYDZs6TleXxaMCPRYxt
      clientSecret: tdwuoLQpSPi4tZrVpNzDoQMWYP8KCDo4VCSie2K_LIuXItBiN3hiG20-.bBRItuf
    default-job-worker-tenant-ids:

server:
  error:
    include-message: always
  port: 8081

storage:
  database:
    url: postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

spring:
  application:
    name: isurance-service
  r2dbc:
    url: r2dbc:${storage.database.url}
    username: ${storage.database.username}
    password: ${storage.database.password}
    pool:
      enabled: true
      initial-size: 10
      max-size: 30
      max-idle-time: 1m
  flyway:
    url: jdbc:${storage.database.url}
    user: ${storage.database.username}
    password: ${storage.database.password}
    baseline-on-migrate: true
    baseline-version: 0
    clean-on-validation-error: false

client:
  payment-service:
    url: localhost:8082
  risk-service:
    url: localhost:8083